- name: display variables
  hosts: all
  vars: ### variable module 
    Variable: global_variable ### global variable and this is the name of the variable 
  tasks: 
    - name: display global variables
      debug:
        msg: this is the {{Variable}} 

    - name: display local variables
      vars:  ### scope of local variable is within the task outside the it won't work 
       Variable: local_variable
      debug:
        msg: this is the {{Variable}}

 