- name: Demo on using register 
  hosts: all
  tasks:
    - name: Execute Shell Command ### the name is must for every module 
      shell: uptime
      register: OUT ###the output of the shell command is register/stored in "Out" variable can have any variable name
    
    - name: Printing uptime variable 
      debug:
        msg: "{{OUT.stdout}}"
    - name: Getting the status of the uptime command by .rc
      set_fact:
       STATUS: "{{OUT.rc}}"
    - name: Printing status of the uptime command
      debug:
       msg: "status of the uptime command {{STATUS}}"