- name: Demo on using register 
  hosts: all
  tasks:
    - name: Execute Shel Command 
      shell: uptime
      register: OUT ###the output of the shell command is register/stored in "Out" variable can have any variable name
    
   
